# Generated by Django 5.0.14 on 2026-04-08 20:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('trips', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_type', models.CharField(choices=[('fuel', 'Fuel'), ('toll', 'Toll'), ('advance', 'Advance'), ('allowance', 'Allowance'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='expenses/receipts/%Y/%m/')),
                ('payment_mode', models.CharField(blank=True, choices=[('cash', 'Cash'), ('phonepay', 'PhonePe'), ('gpay', 'Google Pay'), ('paytm', 'Paytm'), ('upi', 'UPI'), ('card', 'Card'), ('other', 'Other')], max_length=20)),
                ('is_deducted', models.BooleanField(default=False)),
                ('deducted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='drivers.driver')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='trips.trip')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'expenses',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['driver', 'expense_date'], name='expenses_driver__656a3d_idx'), models.Index(fields=['vehicle', 'expense_date'], name='expenses_vehicle_33ff4f_idx'), models.Index(fields=['expense_type'], name='expenses_expense_272666_idx'), models.Index(fields=['expense_date'], name='expenses_expense_43600a_idx'), models.Index(fields=['is_deducted'], name='expenses_is_dedu_f07bfa_idx')],
            },
        ),
    ]
