# Generated by Django 5.0.14 on 2026-05-03 06:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_restructure_expense_add_fastag_company'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_driver__656a3d_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_expense_43600a_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_is_dedu_f07bfa_idx',
        ),
        migrations.RenameIndex(
            model_name='companyexpense',
            new_name='company_exp_expense_b0c6dc_idx',
            old_name='co_exp_type_month_idx',
        ),
        migrations.RenameIndex(
            model_name='companyexpense',
            new_name='company_exp_month_y_e83db8_idx',
            old_name='co_exp_month_year_idx',
        ),
        migrations.RenameIndex(
            model_name='companyexpense',
            new_name='company_exp_expense_0cbcbe_idx',
            old_name='co_exp_date_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_vehicle_a64c86_idx',
            old_name='expense_vehicle_month_idx',
        ),
        migrations.RenameIndex(
            model_name='fastagrecord',
            new_name='fastag_reco_month_y_f75f64_idx',
            old_name='fastag_month_year_idx',
        ),
        migrations.RenameIndex(
            model_name='fastagrecord',
            new_name='fastag_reco_status_715dcd_idx',
            old_name='fastag_status_idx',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
        migrations.AddField(
            model_name='expense',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['month_year'], name='expenses_month_y_8598b5_idx'),
        ),
    ]
