# Generated by Django 5.0.14 on 2026-04-08 20:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=12)),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'db_table': 'drivers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverVehicleMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary vehicle for this driver')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_mappings', to='drivers.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_mappings', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Driver-Vehicle Mapping',
                'verbose_name_plural': 'Driver-Vehicle Mappings',
                'db_table': 'driver_vehicle_mappings',
                'ordering': ['-assigned_at'],
                'unique_together': {('driver', 'vehicle')},
            },
        ),
    ]
