# Generated by Django 5.0.14 on 2026-04-08 20:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'db_table': 'vendors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('pickup', 'Pickup'), ('truck', 'Truck'), ('van', 'Van'), ('bike', 'Bike'), ('other', 'Other')], default='pickup', max_length=50)),
                ('owner_type', models.CharField(choices=[('owner', 'Owner'), ('vendor', 'Vendor')], max_length=20)),
                ('km_rate', models.DecimalField(decimal_places=2, default=0, help_text='Rate per KM for vendor vehicles', max_digits=10)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, help_text='Base salary for owner vehicle drivers', max_digits=10)),
                ('fuel_average', models.DecimalField(blank=True, decimal_places=2, help_text='KM per liter', max_digits=5, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('fc_expiry', models.DateField(blank=True, help_text='Fitness Certificate Expiry', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='vehicles.vendor')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicles',
                'ordering': ['vehicle_number'],
            },
        ),
    ]
