# Generated by Django 5.0.14 on 2026-04-08 20:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('salary', 'Salary'), ('vendor_payment', 'Vendor Payment'), ('advance', 'Advance'), ('reimbursement', 'Reimbursement')], max_length=20)),
                ('month_year', models.DateField()),
                ('total_trips', models.IntegerField(default=0)),
                ('total_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('km_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('km_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_fuel_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_advance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_toll_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='drivers.driver')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='vehicles.vehicle')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='vehicles.vendor')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-month_year', '-created_at'],
                'indexes': [models.Index(fields=['driver', 'month_year'], name='payments_driver__e93440_idx'), models.Index(fields=['vehicle', 'month_year'], name='payments_vehicle_ecde50_idx'), models.Index(fields=['vendor', 'month_year'], name='payments_vendor__261020_idx'), models.Index(fields=['status'], name='payments_status_d621e5_idx'), models.Index(fields=['month_year'], name='payments_month_y_ba61ee_idx')],
            },
        ),
    ]
