# Generated by Django 5.0.14 on 2026-05-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_add_manual_override_flags_to_settlement'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vehiclesettlement',
            new_name='vehicle_set_status_2d11cb_idx',
            old_name='settlement_status_idx',
        ),
        migrations.RenameIndex(
            model_name='vehiclesettlement',
            new_name='vehicle_set_month_y_c17099_idx',
            old_name='settlement_month_year_idx',
        ),
        migrations.AddField(
            model_name='vehiclesettlement',
            name='billing_mode',
            field=models.CharField(choices=[('full_month', 'Full Month Rate'), ('daily_rate', 'Daily Rate')], default='full_month', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiclesettlement',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehiclesettlement',
            name='extra_km_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehiclesettlement',
            name='extra_km_units',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehiclesettlement',
            name='km_slab',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehiclesettlement',
            name='overpaid_prev_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehiclesettlement',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('full', 'Full'), ('overpaid', 'Overpaid')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiclesettlement',
            name='pending_prev_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehiclesettlement',
            name='rent_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
