# Generated by Django 5.0.14 on 2026-04-08 20:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_date', models.DateField()),
                ('warehouse', models.CharField(default='B3 WH', max_length=50)),
                ('dispatch_time_1', models.TimeField(blank=True, null=True)),
                ('store_name_1', models.CharField(blank=True, max_length=200)),
                ('one_way_km_1', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dispatch_time_2', models.TimeField(blank=True, null=True)),
                ('store_name_2', models.CharField(blank=True, max_length=200)),
                ('one_way_km_2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('gate_pass_image', models.ImageField(blank=True, null=True, upload_to='trips/gate_pass/%Y/%m/')),
                ('map_screenshot', models.ImageField(blank=True, null=True, upload_to='trips/maps/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_trips', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='drivers.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'db_table': 'trips',
                'ordering': ['-trip_date', '-created_at'],
                'indexes': [models.Index(fields=['driver', 'trip_date'], name='trips_driver__b1b2c7_idx'), models.Index(fields=['vehicle', 'trip_date'], name='trips_vehicle_526bd6_idx'), models.Index(fields=['status'], name='trips_status_b30e85_idx'), models.Index(fields=['trip_date'], name='trips_trip_da_e2166f_idx')],
            },
        ),
    ]
