# Generated by Django 5.0.14 on 2026-04-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_seed_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='gate_pass_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='trips/gate_pass/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='trip',
            name='map_screenshot_2',
            field=models.ImageField(blank=True, null=True, upload_to='trips/maps/%Y/%m/'),
        ),
    ]
