import { useMemo } from 'react';
import { useQuery } from 'react-query';
import { Calendar, CreditCard, Truck, Wallet } from 'lucide-react';
import api from '../../services/api';

const PaymentsManagement = () => {
  const { data, isLoading } = useQuery({
    queryKey: ['payments'],
    queryFn: () => api.get('/payments/'),
  });

  const payments = data?.data?.data?.payments || [];

  const stats = useMemo(
    () => ({
      total: payments.length,
      pending: payments.filter((payment) => payment.status === 'pending').length,
      paid: payments.filter((payment) => payment.status === 'paid').length,
      totalAmount: payments.reduce((sum, payment) => sum + Number(payment.final_amount || 0), 0),
    }),
    [payments]
  );

  if (isLoading) {
    return (
      <div className="flex h-64 items-center justify-center">
        <div className="h-8 w-8 animate-spin rounded-full border-4 border-blue-600 border-t-transparent" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Payments</h1>
        <p className="mt-1 text-sm text-gray-500">Track salary and vendor payment records generated by the backend.</p>
      </div>

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <div className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm">
          <div className="text-sm text-gray-500">Payment records</div>
          <div className="mt-2 text-3xl font-bold text-gray-900">{stats.total}</div>
        </div>
        <div className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm">
          <div className="text-sm text-gray-500">Pending</div>
          <div className="mt-2 text-3xl font-bold text-gray-900">{stats.pending}</div>
        </div>
        <div className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm">
          <div className="text-sm text-gray-500">Paid</div>
          <div className="mt-2 text-3xl font-bold text-gray-900">{stats.paid}</div>
        </div>
        <div className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm">
          <div className="text-sm text-gray-500">Total amount</div>
          <div className="mt-2 text-3xl font-bold text-gray-900">
            Rs. {stats.totalAmount.toLocaleString('en-IN')}
          </div>
        </div>
      </div>

      <div className="space-y-4">
        {payments.length === 0 ? (
          <div className="rounded-2xl border border-dashed border-gray-300 bg-white p-10 text-center text-gray-500">
            No payments created yet.
          </div>
        ) : (
          payments.map((payment) => (
            <div key={payment.id} className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm">
              <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
                <div>
                  <div className="flex flex-wrap items-center gap-3">
                    <span className="rounded-full bg-blue-100 px-3 py-1 text-xs font-semibold uppercase tracking-wide text-blue-700">
                      {payment.payment_type}
                    </span>
                    <span className={`rounded-full px-3 py-1 text-xs font-semibold ${
                      payment.status === 'paid'
                        ? 'bg-green-100 text-green-700'
                        : payment.status === 'pending'
                          ? 'bg-yellow-100 text-yellow-700'
                          : 'bg-gray-100 text-gray-700'
                    }`}>
                      {payment.status}
                    </span>
                  </div>

                  <h2 className="mt-4 text-lg font-semibold text-gray-900">{payment.recipient_name}</h2>
                  <div className="mt-3 flex flex-wrap gap-4 text-sm text-gray-500">
                    <span className="inline-flex items-center gap-2">
                      <Truck className="h-4 w-4" />
                      {payment.vehicle_number || 'No vehicle linked'}
                    </span>
                    <span className="inline-flex items-center gap-2">
                      <Calendar className="h-4 w-4" />
                      {new Date(payment.month_year).toLocaleDateString('en-IN', {
                        month: 'short',
                        year: 'numeric',
                      })}
                    </span>
                  </div>
                </div>

                <div className="grid gap-3 sm:grid-cols-2 lg:min-w-[320px]">
                  <div className="rounded-xl bg-gray-50 p-4">
                    <div className="flex items-center gap-2 text-xs uppercase tracking-wide text-gray-500">
                      <Wallet className="h-4 w-4" />
                      Final amount
                    </div>
                    <div className="mt-2 text-sm font-medium text-gray-900">
                      Rs. {Number(payment.final_amount || 0).toLocaleString('en-IN')}
                    </div>
                  </div>
                  <div className="rounded-xl bg-gray-50 p-4">
                    <div className="flex items-center gap-2 text-xs uppercase tracking-wide text-gray-500">
                      <CreditCard className="h-4 w-4" />
                      Status
                    </div>
                    <div className="mt-2 text-sm font-medium capitalize text-gray-900">{payment.status}</div>
                  </div>
                </div>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
};

export default PaymentsManagement;
